### ISSUE TITLE
PatchIt! Version 1.1.2 Checklist

### ISSUE THREAD

**Issue by le717** [le717/PatchIt#12]
An (semi-incomplete) list of everything that must be done before 1.1.2 is released.
- [x] Break up a lot of the functions into smaller scripts
- [x] Add code to add new lines in a Patch Description (see #13)
- [x] Integrate RunAsAdmin for Administrator rights access
- [x] Trim out Tkinter files to discover just what is need to run
- [x] Improved 16x16 icon
- [x] Update freezing documentation with new folder paths
  and `wget` (see #17)
- [x] Freeze Uninstaller when freezing **PatchIt!** itself as part of process
- [x] Update all `setup.py` scripts to use "GPLv3" for the license field instead of "GNU GPLv3"
- [x] Make all scripts use `import constants as const` syntax (see #18)
- [x] Improved installer sidebar graphic
- [x] Any reported bugs
- [x] [Any open Issues for this milestone](https://github.com/le717/PatchIt/issues?milestone=3&state=open)
