### ISSUE TITLE
PatchIt! Version 1.1.3 Checklist

### ISSUE THREAD

**Issue by le717** [le717/PatchIt#16]
Semi-complete list of all changes that must be done before the release of **PatchIt! Version 1.1.3**.
- [ ] Add code to serve as a progress bar until GUI is added (see #11)
- [ ] Restructure all scripts in OOP
  - [ ] Patch-related
  - [ ] Settings-related
- [x] Drop all _LEGO® LOCO_ code (see #20)
- [x] Remove Legacy Patch Installation support (`Patch/legacyinstall.pyw`) (see #19)
- [ ] Further script renaming and project organization
- [ ] Full support of _LEGO® Racers_ 2001 release
- [ ] Finish improving installer sidebar graphic
- [ ] Make as much code as possible pass flake8 and pep257
- [ ] Any reported bugs
- [ ] [Any open Issues for this milestone](https://github.com/le717/PatchIt/milestones/1.1.3)
