### ISSUE TITLE
PatchIt! Version 1.1.1 Checklist

### ISSUE THREAD

**Issue by le717** [le717/PatchIt#8]
Things that must be done before **PatchIt! Version 1.1.1** will be released, listed in no particular order:
- [x] Change Patch Archive extension to _.PiA_
- [x] Update PiP Format V1.1 documentation with _.PiA_ extension
- [x] Add Credits Page to Website/Other Website Issues (see Issue #9)
- [x] Finish updating [`PiP Format V1.1.md`](about:blank) PiA  Archive section
- [x] Add TAR Archive extraction code to [`Patch/modernextract.pyw`](about:blank)
- [x] Add TAR Archive compression code to [`Patch/moderncompress.pyw`](about:blank)
- [x] Finish writing whitelist code for TAR Archive compression
- [x] Any bugs from RC testers
- [x] Any [open Issues for this milestone](https://github.com/le717/PatchIt/issues?milestone=2&state=open)
- [x] Make sure [Documentation](https://github.com/le717/PatchIt/tree/rewrite/Documentation) is up-to-date
- [x] Add file encoding check when reading game settings during installation process
- [x] Possibly add new **PatchIt!** Settings
- [x] Write compiling directions for Inno Setup Installer
- [x] Final version for PiP Format
- [x] Move old downloads from Readme.md to releases page 
- [x] Release! :smiley:

**Comment by le717** [comment]
**PatchIt! Version 1.1.1 Stable is _finally_ released!**
